const WS='wss://ws.derivws.com/websockets/v3?app_id=1089',S=['1HZ10V','1HZ15V','1HZ25V','1HZ30V','1HZ50V','1HZ75V','1HZ90V','1HZ100V'],N={1HZ10V:'VOL 10 (1S)',1HZ15V:'VOL 15 (1S)',1HZ25V:'VOL 25 (1S)',1HZ30V:'VOL 30 (1S)',1HZ50V:'VOL 50 (1S)',1HZ75V:'VOL 75 (1S)',1HZ90V:'VOL 90 (1S)',1HZ100V:'VOL 100 (1S)'},$=x=>document.getElementById(x);let ws,a=[],ep=[],last=0,retry;
function dg(x){let s=String(x),p=s.indexOf('.');return +((p<0?s:s.slice(p+1)).replace(/\D/g,'').slice(-1)||0)}function C(x){let c=Array(10).fill(0);x.forEach(v=>c[v]++);return c}function lead(x){let c=C(x),m=Math.max(...c);return c.indexOf(m)}function P(x,n){return n?100*x/n:0}function H(x){let c=C(x),n=x.length;return c.reduce((z,v)=>v?z-v/n*Math.log2(v/n):z,0)}function run(x,d){let n=0;for(let i=x.length-1;i>=0&&x[i]===d;i--)n++;return n}function conn(on,msg){$('led').className=on?'on':'';$('conn').textContent=on?'LIVE':'OFFLINE';$('status').textContent=msg}
function start(){connect($('symbol').value,1)}function connect(s,clear){if(clear){a=[];ep=[];last=0}if(ws)try{ws.close()}catch(e){}$('marketName').textContent=N[s];conn(0,'Connecting to public Deriv market data…');ws=new WebSocket(WS);ws.onopen=()=>{conn(1,'LIVE — public Deriv tick feed');ws.send(JSON.stringify({ticks_history:s,count:200,end:'latest',style:'ticks'}));ws.send(JSON.stringify({ticks:s,subscribe:1}))};ws.onmessage=e=>msg(e.data);ws.onerror=()=>conn(0,'Feed error — retrying…');ws.onclose=()=>{conn(0,'Feed disconnected — retrying…');clearTimeout(retry);retry=setTimeout(()=>connect(s,0),3500)}}
function msg(raw){let d;try{d=JSON.parse(raw)}catch(e){return}if(d.error){conn(0,d.error.message);return}if(d.msg_type==='history'&&d.history){let p=d.history.prices||[],t=d.history.times||[];for(let i=0;i<p.length;i++){if(+t[i]===last)continue;a.push(+p[i]);ep.push(+t[i]);last=+t[i]}trim();draw();return}if(d.msg_type==='tick'&&d.tick){let q=+d.tick.quote,e=+d.tick.epoch;if(e===last)return;last=e;a.push(q);ep.push(e);trim();draw()}}
function trim(){if(a.length>600){let k=a.length-600;a.splice(0,k);ep.splice(0,k)}}
function draw(){let x=a.slice(-200),d=x.map(dg),c=C(d),l=lead(d),n=d.length;$('price').textContent=n?Number(x[n-1]).toLocaleString(undefined,{maximumFractionDigits:5}):'—';$('ticksCount').textContent=n+' TICKS';$('win').textContent=n;$('ent').textContent=n?H(d).toFixed(2):'—';$('streak').textContent=n?run(d,d[n-1]):'—';$('spread').textContent=n?Math.max(...d)-Math.min(...d):'—';$('lastDigits').innerHTML=d.slice(-10).map(v=>'<i class="'+(v===l?'hot':'')+'">'+v+'</i>').join('');if(ep.length>1){let z=Math.max(1,ep[ep.length-1]-ep[Math.max(0,ep.length-51)]);$('rate').textContent=(Math.min(50,ep.length-1)/z).toFixed(2)+' t/s';$('epoch').textContent=new Date(ep[ep.length-1]*1000).toLocaleTimeString([],{hour12:false})}$('log').textContent=d.slice(-180).join(' ');$('logCount').textContent=d.length+' digits';digits(d,c);matches(d,c,l);parity(d);threshold(d);validation(d);chart(x)}
function digits(d,c){let m=Math.max(1,...c);$('digitGrid').innerHTML=c.map((v,i)=>'<div><b>'+i+'</b><small>'+P(v,d.length).toFixed(1)+'%</small><em style="width:'+P(v,m)+'%"></em></div>').join('')}
function matches(d,c,l){let m=P(c[l],d.length),q=100-m;$('matchDigit').textContent=l;$('matchRate').textContent=m.toFixed(1)+'%';$('diffRate').textContent=q.toFixed(1)+'%';$('matchRuns').textContent='MATCH RUN '+run(d,l);$('diffRuns').textContent='DIFFER RUN '+run(d,l===0?1:0);$('matchSample').textContent='SAMPLE '+d.length}
function parity(d){let e=d.filter(x=>x%2===0).length,o=d.length-e;$('evenBar').style.width=P(e,d.length)+'%';$('oddBar').style.width=P(o,d.length)+'%';$('evenPct').textContent=P(e,d.length).toFixed(1)+'%';$('oddPct').textContent=P(o,d.length).toFixed(1)+'%';$('evenCount').textContent=e;$('oddCount').textContent=o}
function threshold(d){let h='';for(let t=0;t<10;t++){let o=d.filter(x=>x>t).length,u=d.filter(x=>x<t).length;h+='<div class=barrow><span>Over '+t+'</span><i><b style="width:'+P(o,d.length)+'%"></b></i><strong>'+P(o,d.length).toFixed(1)+'%</strong></div><div class=barrow><span>Under '+t+'</span><i><b style="width:'+P(u,d.length)+'%"></b></i><strong>'+P(u,d.length).toFixed(1)+'%</strong></div>'}$('thresholdBars').innerHTML=h}
function validation(d){let w=Math.min(50,Math.max(20,Math.floor(d.length/3))),m=0,n=0;for(let i=w;i<d.length;i++){let p=lead(d.slice(i-w,i));m+=d[i]===p;n++}$('btm').textContent=P(m,n).toFixed(1)+'%';$('btd').textContent=P(n-m,n).toFixed(1)+'%';$('bs').textContent=n}
function EMA(x,p){if(!x.length)return 0;let k=2/(p+1),e=x[0];for(let i=1;i<x.length;i++)e=x[i]*k+e*(1-k);return e}function RSI(x,p=14){if(x.length<=p)return 50;let g=0,l=0;for(let i=x.length-p;i<x.length;i++){let z=x[i]-x[i-1];z>0?g+=z:l-=z}return l?100-100/(1+g/l):100}function BB(x,p=20){x=x.slice(-p);let m=x.reduce((a,b)=>a+b,0)/x.length,s=Math.sqrt(x.reduce((a,b)=>a+(b-m)**2,0)/x.length);return{m,u:m+2*s,l:m-2*s}}
function chart(x){let cv=$('chart'),r=cv.getBoundingClientRect(),d=devicePixelRatio||1,w=Math.max(1,r.width*d),h=Math.max(1,r.height*d);if(cv.width!==w||cv.height!==h){cv.width=w;cv.height=h}let g=cv.getContext('2d'),v=x.slice(-100);g.clearRect(0,0,w,h);if(v.length<2)return;let b=v.map((_,i)=>BB(v.slice(0,i+1),Math.min(20,i+1))),e=v.map((_,i)=>EMA(v.slice(0,i+1),20)),lo=Math.min(...v,...b.map(z=>z.l)),hi=Math.max(...v,...b.map(z=>z.u)),sx=i=>i/(v.length-1)*w,sy=q=>h-6-(q-lo)/(hi-lo||1)*(h-12);function line(q,c){g.beginPath();g.strokeStyle=c;g.lineWidth=1.5;q.forEach((z,i)=>i?g.lineTo(sx(i),sy(z)):g.moveTo(sx(i),sy(z)));g.stroke()}line(v,'#ff5a1f');line(e,'#54a7ff');line(b.map(z=>z.u),'#f5c84b');line(b.map(z=>z.l),'#f5c84b');let z=BB(x),em=EMA(v,20);$('ema').textContent=em.toFixed(5);$('rsi').textContent=RSI(v).toFixed(1);$('bbmid').textContent=z.m.toFixed(5);$('bbrange').textContent=z.l.toFixed(5)+' — '+z.u.toFixed(5)}
function tab(id,b){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');b.classList.add('active')}function go(id,b){$(id).scrollIntoView({behavior:'smooth'});document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}
function scanMarkets(){if(window.scanning)return;window.scanning=1;$('scanState').textContent='SCANNING…';let out=[],left=S.length;S.forEach(s=>{let q=new WebSocket(WS),done=0;q.onopen=()=>q.send(JSON.stringify({ticks_history:s,count:100,end:'latest',style:'ticks'}));q.onmessage=e=>{let d;try{d=JSON.parse(e.data)}catch(x){return}if(d.msg_type==='history'&&!done){done=1;let p=d.history.prices||[],ds=p.map(dg),c=C(ds),l=lead(ds);out.push({s,p:p.at(-1),l,r:P(c[l],ds.length)});q.close();if(!--left)showScan(out)}};q.onerror=()=>{if(!done){done=1;if(!--left)showScan(out)}}})}
function showScan(o){window.scanning=0;$('scanState').textContent='UPDATED';let mx=Math.max(1,...o.map(x=>x.r));$('markets').innerHTML=S.map(s=>{let x=o.find(z=>z.s===s)||{p:'—',l:'—',r:0};return '<div class="market '+(s===$('symbol').value?'sel':'')+'" onclick="$(\'symbol\').value=\''+s+'\';start()"><b>'+N[s]+'</b><strong>'+((x.p==='—')?'—':Number(x.p).toLocaleString(undefined,{maximumFractionDigits:5}))+'</strong><div class=meter><i style="width:'+P(x.r,mx)+'%"></i></div><small><span>digit '+x.l+'</span><span>'+x.r.toFixed(1)+'%</span></small></div>'}).join('')}
$('markets').innerHTML=S.map(s=>'<div class="market '+(s===$('symbol').value?'sel':'')+'" onclick="$(\'symbol\').value=\''+s+'\';start()"><b>'+N[s]+'</b><strong>—</strong><div class=meter><i style="width:0%"></i></div><small><span>awaiting data</span><span>—</span></small></div>').join('');scanMarkets();window.addEventListener('resize',()=>chart(a.slice(-100)));
